using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ErrorOr.Generators.Emitters;

/// <summary>
///     Emits a source-generated <c>IValidatableInfoResolver</c> that bridges ErrorOrX endpoints
///     with .NET 10's <c>Microsoft.Extensions.Validation</c> infrastructure.
/// </summary>
/// <remarks>
///     The built-in ValidationsGenerator discovers DTO types from Minimal API handler
///     delegates, but ErrorOrX wraps user handlers behind generated Invoke_EpN delegates
///     whose parameters are HttpContext — not the original DTOs. This emitter closes
///     that cross-assembly visibility gap.
/// </remarks>
internal static class ValidationResolverEmitter
{
    public static void Emit(SourceProductionContext spc, ImmutableArray<EndpointDescriptor> endpoints)
    {
        var validatableTypes = CollectValidatableTypes(endpoints);
        if (validatableTypes.Count is 0) return;

        var code = new StringBuilder();
        code.AppendLine(GeneratedCodeHelpers.AutoGeneratedHeader("ErrorOr.Generators"));
        code.AppendLine("#pragma warning disable ASP0029 // Type is for evaluation purposes only");
        code.AppendLine(GeneratedCodeHelpers.NullableEnable);
        code.AppendLine();
        code.AppendLine("namespace ErrorOr.Generated");
        code.AppendLine("{");
        code.AppendLine("    using System;");
        code.AppendLine("    using System.Reflection;");
        code.AppendLine("    using System.ComponentModel.DataAnnotations;");

        EmitResolverClass(code, validatableTypes);

        foreach (var type in validatableTypes)
        {
            EmitTypeInfoClass(code, type);
            EmitPropertyInfoClasses(code, type);
        }

        EmitValidationAttributeCache(code);

        code.AppendLine("}");

        spc.AddSource("ErrorOrValidationResolver.g.cs", SourceText.From(code.ToString(), Encoding.UTF8));
    }

    private static List<ValidatableTypeDescriptor> CollectValidatableTypes(
        ImmutableArray<EndpointDescriptor> endpoints)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var types = new List<ValidatableTypeDescriptor>();

        foreach (var ep in endpoints)
        {
            foreach (var param in ep.HandlerParameters.AsImmutableArray())
            {
                if (!param.RequiresValidation || param.ValidatableProperties.IsDefaultOrEmpty) continue;

                if (seen.Add(param.TypeFqn))
                    types.Add(new ValidatableTypeDescriptor(param.TypeFqn, param.ValidatableProperties));
            }
        }

        types.Sort(static (a, b) => string.CompareOrdinal(a.TypeFqn, b.TypeFqn));
        return types;
    }

    private static void EmitResolverClass(StringBuilder code, List<ValidatableTypeDescriptor> types)
    {
        code.AppendLine();
        code.AppendLine("    /// <summary>");
        code.AppendLine(
            "    /// Generated IValidatableInfoResolver that provides validation metadata for ErrorOrX endpoint DTOs.");
        code.AppendLine("    /// </summary>");
        code.AppendLine(
            $"    internal sealed class ErrorOrValidatableInfoResolver : {WellKnownTypes.Fqn.ValidatableInfoResolver}");
        code.AppendLine("    {");
        code.AppendLine(
            $"        public bool TryGetValidatableTypeInfo(Type type, [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out {WellKnownTypes.Fqn.IValidatableInfo}? validatableInfo)");
        code.AppendLine("        {");

        foreach (var type in types)
        {
            var safeId = type.TypeFqn.SanitizeIdentifier();
            code.AppendLine($"            if (type == typeof({type.TypeFqn}))");
            code.AppendLine("            {");
            code.AppendLine($"                validatableInfo = {safeId}_TypeInfo.Instance;");
            code.AppendLine("                return true;");
            code.AppendLine("            }");
            code.AppendLine();
        }

        code.AppendLine("            validatableInfo = null;");
        code.AppendLine("            return false;");
        code.AppendLine("        }");
        code.AppendLine();
        code.AppendLine(
            $"        public bool TryGetValidatableParameterInfo(ParameterInfo parameterInfo, [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out {WellKnownTypes.Fqn.IValidatableInfo}? validatableInfo)");
        code.AppendLine("        {");
        code.AppendLine("            validatableInfo = null;");
        code.AppendLine("            return false;");
        code.AppendLine("        }");
        code.AppendLine("    }");
    }

    private static void EmitTypeInfoClass(StringBuilder code, ValidatableTypeDescriptor type)
    {
        var safeId = type.TypeFqn.SanitizeIdentifier();
        code.AppendLine();
        code.AppendLine(
            $"    internal sealed class {safeId}_TypeInfo : {WellKnownTypes.Fqn.ValidatableTypeInfoBase}");
        code.AppendLine("    {");
        code.AppendLine($"        public static readonly {safeId}_TypeInfo Instance = new();");
        code.AppendLine();
        code.AppendLine(
            $"        private {safeId}_TypeInfo() : base(typeof({type.TypeFqn}), new {WellKnownTypes.Fqn.ValidatablePropertyInfoBase}[]");
        code.AppendLine("        {");

        foreach (var prop in type.Properties.AsImmutableArray())
        {
            var propId = $"{safeId}_{prop.Name}_Prop";
            code.AppendLine($"            new {propId}(),");
        }

        code.AppendLine("        }) { }");
        code.AppendLine();
        code.AppendLine(
            "        protected override ValidationAttribute[] GetValidationAttributes() => [];");
        code.AppendLine("    }");
    }

    private static void EmitPropertyInfoClasses(StringBuilder code, ValidatableTypeDescriptor type)
    {
        var safeId = type.TypeFqn.SanitizeIdentifier();
        foreach (var prop in type.Properties.AsImmutableArray())
        {
            var propId = $"{safeId}_{prop.Name}_Prop";
            code.AppendLine();
            code.AppendLine(
                $"    internal sealed class {propId} : {WellKnownTypes.Fqn.ValidatablePropertyInfoBase}");
            code.AppendLine("    {");
            code.AppendLine(
                $"        public {propId}() : base(typeof({type.TypeFqn}), typeof({prop.TypeFqn}), \"{prop.Name}\", \"{prop.DisplayName}\") {{ }}");
            code.AppendLine();
            // Recover the declared ValidationAttributes at runtime from the [DynamicallyAccessedMembers]-rooted
            // Type instead of constructing attribute instances here. Emitting e.g. `new MinLengthAttribute(1)`
            // calls a [RequiresUnreferencedCode] ctor and trips IL2026 under PublishAot. `typeof(T)` as a literal
            // satisfies the cache's DAM requirement with zero trim warnings — the .NET 10 validation pattern.
            code.AppendLine(
                $"        protected override ValidationAttribute[] GetValidationAttributes() => ValidationAttributeCache.GetPropertyValidationAttributes(typeof({type.TypeFqn}), \"{prop.Name}\");");
            code.AppendLine("    }");
        }
    }

    /// <summary>
    ///     Emits a file-scoped cache that recovers a property's <c>ValidationAttribute</c>s via
    ///     reflection over a <c>[DynamicallyAccessedMembers]</c>-rooted <c>System.Type</c> — the
    ///     trim-safe pattern used by .NET 10's own <c>Microsoft.Extensions.Validation</c> generator (whose
    ///     <c>ValidationAttributeCache</c> is <c>file</c>-scoped and not a public API, so each generator emits
    ///     its own copy; the <c>file</c> modifier prevents collision when both run in one assembly). The DAM
    ///     annotation flows through the <c>CacheKey</c> record into the reflective lookup so the trimmer
    ///     preserves the metadata. Covers the record primary-constructor-parameter case (case-insensitive).
    /// </summary>
    private static void EmitValidationAttributeCache(StringBuilder code)
    {
        code.AppendLine();
        code.AppendLine("    file static class ValidationAttributeCache");
        code.AppendLine("    {");
        code.AppendLine("        private sealed record CacheKey(");
        code.AppendLine(
            "            [param: global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]");
        code.AppendLine(
            "            [property: global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]");
        code.AppendLine("            global::System.Type ContainingType,");
        code.AppendLine("            string PropertyName);");
        code.AppendLine();
        code.AppendLine(
            "        private static readonly global::System.Collections.Concurrent.ConcurrentDictionary<CacheKey, global::System.ComponentModel.DataAnnotations.ValidationAttribute[]> s_propertyCache = new();");
        code.AppendLine();
        code.AppendLine(
            "        public static global::System.ComponentModel.DataAnnotations.ValidationAttribute[] GetPropertyValidationAttributes(");
        code.AppendLine(
            "            [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties | global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]");
        code.AppendLine("            global::System.Type containingType,");
        code.AppendLine("            string propertyName)");
        code.AppendLine("        {");
        code.AppendLine("            var key = new CacheKey(containingType, propertyName);");
        code.AppendLine("            return s_propertyCache.GetOrAdd(key, static k =>");
        code.AppendLine("            {");
        code.AppendLine(
            "                var results = new global::System.Collections.Generic.List<global::System.ComponentModel.DataAnnotations.ValidationAttribute>();");
        code.AppendLine();
        code.AppendLine("                var property = k.ContainingType.GetProperty(k.PropertyName);");
        code.AppendLine("                if (property != null)");
        code.AppendLine(
            "                    results.AddRange(global::System.Reflection.CustomAttributeExtensions.GetCustomAttributes<global::System.ComponentModel.DataAnnotations.ValidationAttribute>(property, inherit: true));");
        code.AppendLine();
        code.AppendLine("                // Records place validation attributes on the primary-constructor parameter.");
        code.AppendLine("                foreach (var constructor in k.ContainingType.GetConstructors())");
        code.AppendLine("                {");
        code.AppendLine("                    var parameter = global::System.Linq.Enumerable.FirstOrDefault(");
        code.AppendLine("                        constructor.GetParameters(),");
        code.AppendLine(
            "                        p => string.Equals(p.Name, k.PropertyName, global::System.StringComparison.OrdinalIgnoreCase));");
        code.AppendLine("                    if (parameter != null)");
        code.AppendLine("                    {");
        code.AppendLine(
            "                        results.AddRange(global::System.Reflection.CustomAttributeExtensions.GetCustomAttributes<global::System.ComponentModel.DataAnnotations.ValidationAttribute>(parameter, inherit: true));");
        code.AppendLine("                        break;");
        code.AppendLine("                    }");
        code.AppendLine("                }");
        code.AppendLine();
        code.AppendLine("                return results.ToArray();");
        code.AppendLine("            });");
        code.AppendLine("        }");
        code.AppendLine("    }");
    }
}
