using Microsoft.CodeAnalysis;

namespace ErrorOr.Generators;

/// <summary>
///     Marker-attribute emission via <c>RegisterPostInitializationOutput</c>.
///     Defines <c>[Get]</c>, <c>[Post]</c>, <c>[Put]</c>, <c>[Delete]</c>, <c>[Patch]</c>,
///     <c>[Head]</c>, <c>[Options]</c>, <c>[Trace]</c>, <c>[ErrorOrEndpoint]</c>,
///     <c>[ProducesError]</c>, <c>[AcceptedResponse]</c>, <c>[ReturnsError]</c>, and
///     <c>[RouteGroup]</c> as compile-time-injected types in the consumer's <c>ErrorOr</c>
///     namespace. Must live with this generator (not <c>OpenApiTransformerGenerator</c>)
///     because <c>ForAttributeWithMetadataName</c> only sees types injected by the same generator.
/// </summary>
public sealed partial class ErrorOrEndpointGenerator
{
    private static void EmitAttributes(IncrementalGeneratorPostInitializationContext context)
    {
        const string Source = """
                              // <auto-generated/>
                              #nullable enable

                              namespace ErrorOr
                              {
                                  /// <summary>
                                  /// Marks a static method as an ErrorOr endpoint with explicit HTTP method and route.
                                  /// Prefer using [Get], [Post], [Put], [Delete], or [Patch] for standard HTTP methods.
                                  /// </summary>
                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
                                  public sealed class ErrorOrEndpointAttribute : global::System.Attribute
                                  {
                                      public ErrorOrEndpointAttribute(string httpMethod, string route)
                                      {
                                          HttpMethod = httpMethod;
                                          Route = route;
                                      }
                                      public string HttpMethod { get; }
                                      public string Route { get; }
                                  }

                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
                                  public sealed class GetAttribute : global::System.Attribute
                                  {
                                      public GetAttribute(string route) => Route = route;
                                      public string Route { get; }
                                  }

                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
                                  public sealed class PostAttribute : global::System.Attribute
                                  {
                                      public PostAttribute(string route) => Route = route;
                                      public string Route { get; }
                                  }

                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
                                  public sealed class PutAttribute : global::System.Attribute
                                  {
                                      public PutAttribute(string route) => Route = route;
                                      public string Route { get; }
                                  }

                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
                                  public sealed class DeleteAttribute : global::System.Attribute
                                  {
                                      public DeleteAttribute(string route) => Route = route;
                                      public string Route { get; }
                                  }

                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
                                  public sealed class PatchAttribute : global::System.Attribute
                                  {
                                      public PatchAttribute(string route) => Route = route;
                                      public string Route { get; }
                                  }

                                  /// <summary>
                                  /// Marks a static method as a HEAD endpoint. ASP.NET Core has no MapHead
                                  /// dedicated overload — the generator emits MapMethods(route, new[] { "HEAD" }, ...).
                                  /// </summary>
                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
                                  public sealed class HeadAttribute : global::System.Attribute
                                  {
                                      public HeadAttribute(string route) => Route = route;
                                      public string Route { get; }
                                  }

                                  /// <summary>
                                  /// Marks a static method as an OPTIONS endpoint. ASP.NET Core has no MapOptions
                                  /// dedicated overload — the generator emits MapMethods(route, new[] { "OPTIONS" }, ...).
                                  /// </summary>
                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
                                  public sealed class OptionsAttribute : global::System.Attribute
                                  {
                                      public OptionsAttribute(string route) => Route = route;
                                      public string Route { get; }
                                  }

                                  /// <summary>
                                  /// Marks a static method as a TRACE endpoint. ASP.NET Core has no MapTrace
                                  /// dedicated overload — the generator emits MapMethods(route, new[] { "TRACE" }, ...).
                                  /// </summary>
                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
                                  public sealed class TraceAttribute : global::System.Attribute
                                  {
                                      public TraceAttribute(string route) => Route = route;
                                      public string Route { get; }
                                  }

                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                                  public sealed class ProducesErrorAttribute : global::System.Attribute
                                  {
                                      public ProducesErrorAttribute(int statusCode, string errorType)
                                      {
                                          StatusCode = statusCode;
                                          ErrorType = errorType;
                                      }
                                      public int StatusCode { get; }
                                      public string ErrorType { get; }
                                  }

                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
                                  public sealed class AcceptedResponseAttribute : global::System.Attribute { }

                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                                  public sealed class ReturnsErrorAttribute : global::System.Attribute
                                  {
                                      public ReturnsErrorAttribute(global::ErrorOr.ErrorType errorType, string errorCode)
                                      {
                                          ErrorType = errorType;
                                          ErrorCode = errorCode;
                                      }
                                      public ReturnsErrorAttribute(int statusCode, string errorCode)
                                      {
                                          StatusCode = statusCode;
                                          ErrorCode = errorCode;
                                          ErrorType = null;
                                      }
                                      public global::ErrorOr.ErrorType? ErrorType { get; }
                                      public int? StatusCode { get; }
                                      public string ErrorCode { get; }
                                  }

                                  /// <summary>
                                  /// Marks a class as a route group for versioned API endpoints.
                                  /// All endpoints in the class will be mapped under the specified path prefix
                                  /// using the eShop-style NewVersionedApi() pattern when combined with [ApiVersion].
                                  /// </summary>
                                  [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
                                  public sealed class RouteGroupAttribute : global::System.Attribute
                                  {
                                      public RouteGroupAttribute(string path) => Path = path;
                                      public string Path { get; }
                                      public string? ApiName { get; set; }
                                  }
                              }
                              """;

        // Use a different file name to avoid conflicts with OpenApiTransformerGenerator
        context.AddSource("ErrorOrEndpointAttributes.Mappings.g.cs", Source);
    }
}
