using ErrorOr.Analyzers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ErrorOr.Generators;

public sealed partial class ErrorOrEndpointGenerator
{
    private static void EmitJsonContext(SourceProductionContext spc, List<string> jsonTypes,
        ImmutableArray<JsonContextInfo> userContexts)
    {
        // If user has their own JsonSerializerContext, emit a helper file instead
        if (userContexts is { IsDefaultOrEmpty: false, Length: > 0 })
        {
            EmitJsonContextHelper(spc, jsonTypes, userContexts);
            return;
        }

        // No user context - emit full ErrorOrJsonContext using IndentedStringBuilder.
        // Default policy is CamelCase + WhenWritingNull — matches the documented opinion for ErrorOrX
        // and the convention every modern web-API client expects. Previously this emit set only
        // DefaultIgnoreCondition, silently defaulting PropertyNamingPolicy to PascalCase — caller's
        // payloads looked "wrong" with no way to discover where the casing came from. If users want
        // PascalCase or another policy, they should supply their own JsonSerializerContext (the
        // EmitJsonContextHelper path detects that and emits guidance instead of overriding).
        var sb = new IndentedStringBuilder();
        sb.AppendLine(GeneratedCodeHelpers.AutoGeneratedHeader("ErrorOr.Generators"));
        sb.AppendLine("// JSON serialization context for Native AOT support.");
        sb.AppendLine(GeneratedCodeHelpers.NullableEnable);
        sb.AppendLine();
        sb.AppendLine(
            "[System.Text.Json.Serialization.JsonSourceGenerationOptions(" +
            "PropertyNamingPolicy = System.Text.Json.Serialization.JsonKnownNamingPolicy.CamelCase, " +
            "DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]");
        foreach (var type in jsonTypes)
            sb.AppendLine($"[System.Text.Json.Serialization.JsonSerializable(typeof({type}))]");
        sb.AppendLine(
            $"[System.Text.Json.Serialization.JsonSerializable(typeof({WellKnownTypes.Fqn.ProblemDetails}))]");
        sb.AppendLine(
            $"[System.Text.Json.Serialization.JsonSerializable(typeof({WellKnownTypes.Fqn.HttpValidationProblemDetails}))]");
        sb.AppendLine(
            "internal partial class ErrorOrJsonContext : System.Text.Json.Serialization.JsonSerializerContext { }");
        spc.AddSource("ErrorOrJsonContext.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitJsonContextHelper(SourceProductionContext spc, List<string> jsonTypes,
        ImmutableArray<JsonContextInfo> userContexts)
    {
        var userContext = userContexts[0]; // Use first context found
        var fullClassName = userContext.Namespace is not null
            ? $"{userContext.Namespace}.{userContext.ClassName}"
            : userContext.ClassName;

        // Collect registered types from user context
        var registeredTypes = new HashSet<string>();
        foreach (var ctx in userContexts)
        {
            foreach (var typeFqn in ctx.SerializableTypes)
                registeredTypes.Add(typeFqn);
        }

        // Find missing types
        var missingTypes = new List<string>();

        // Check endpoint types
        foreach (var type in jsonTypes)
        {
            if (!registeredTypes.Any(type.TypeNamesEqual))
                missingTypes.Add(type);
        }

        // Always check for ProblemDetails and HttpValidationProblemDetails
        var missingProblemDetails = !registeredTypes.Any(static rt =>
            WellKnownTypes.Fqn.ProblemDetails.TypeNamesEqual(rt));
        var missingValidationProblemDetails = !registeredTypes.Any(static rt =>
            WellKnownTypes.Fqn.HttpValidationProblemDetails.TypeNamesEqual(rt));

        if (missingProblemDetails) missingTypes.Add(WellKnownTypes.Fqn.ProblemDetails);

        if (missingValidationProblemDetails) missingTypes.Add(WellKnownTypes.Fqn.HttpValidationProblemDetails);

        // Report EOE025 if user context lacks CamelCase policy
        if (!userContext.HasCamelCasePolicy)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Descriptors.MissingCamelCasePolicy,
                Location.None,
                fullClassName));
        }

        // Report EOE036 if user context is missing ProblemDetails types
        if (missingProblemDetails || missingValidationProblemDetails)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Descriptors.JsonContextMissingProblemDetails,
                Location.None,
                fullClassName));
        }

        // Emit helper file with missing types as comments using IndentedStringBuilder
        var sb = new IndentedStringBuilder();
        sb.AppendLine(GeneratedCodeHelpers.AutoGeneratedHeader("ErrorOr.Generators"));
        sb.AppendLine("// ErrorOrX JSON Context Helper");
        sb.AppendLine();
        sb.AppendLine($"// Detected user JsonSerializerContext: {fullClassName}");
        sb.AppendLine();

        if (missingTypes.Count > 0)
        {
            sb.AppendLine("// ============================================================================");
            sb.AppendLine("// MISSING TYPES - Add these [JsonSerializable] attributes to your context:");
            sb.AppendLine("// ============================================================================");
            sb.AppendLine("//");
            foreach (var type in missingTypes.Distinct())
            {
                var displayType = type.StripGlobalPrefix();
                sb.AppendLine($"// [JsonSerializable(typeof({displayType}))]");
            }

            sb.AppendLine("//");
        }
        else
        {
            sb.AppendLine("// All required types are registered in your JsonSerializerContext.");
        }

        if (!userContext.HasCamelCasePolicy)
        {
            sb.AppendLine();
            sb.AppendLine("// ============================================================================");
            sb.AppendLine("// RECOMMENDED - Add CamelCase policy for web API compatibility:");
            sb.AppendLine("// ============================================================================");
            sb.AppendLine("//");
            sb.AppendLine("// [JsonSourceGenerationOptions(");
            sb.AppendLine("//     PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,");
            sb.AppendLine("//     DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]");
            sb.AppendLine("//");
        }

        // Use same filename as full context to ensure replacement (no stale file issues)
        spc.AddSource("ErrorOrJsonContext.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
