using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ErrorOr.Generators;

public sealed partial class ErrorOrEndpointGenerator
{
    private static void EmitAddErrorOrEndpointsExtension(StringBuilder code, bool hasValidatableTypes = false)
    {
        // Emit fluent builder: AddErrorOrEndpoints() returns IErrorOrEndpointsBuilder
        code.AppendLine("        /// <summary>");
        code.AppendLine("        /// Registers ErrorOr endpoint services and returns a builder for configuration.");
        code.AppendLine("        /// </summary>");
        code.AppendLine("        /// <param name=\"services\">The service collection to configure.</param>");
        code.AppendLine("        /// <returns>A builder for further configuration.</returns>");
        code.AppendLine("        /// <remarks>");
        code.AppendLine("        /// This follows ASP.NET Core's builder pattern (like AddRazorComponents())");
        code.AppendLine("        /// enabling fluent extension method chaining without callback nesting.");
        code.AppendLine("        /// </remarks>");
        code.AppendLine("        /// <example>");
        code.AppendLine("        /// <code>");
        code.AppendLine("        /// builder.Services.AddErrorOrEndpoints()");
        code.AppendLine("        ///     .UseJsonContext&lt;AppJsonSerializerContext&gt;()");
        code.AppendLine("        ///     .WithCamelCase()");
        code.AppendLine("        ///     .WithIgnoreNulls();");
        code.AppendLine("        /// </code>");
        code.AppendLine("        /// </example>");
        code.AppendLine(
            "        public static IErrorOrEndpointsBuilder AddErrorOrEndpoints(this IServiceCollection services)");
        code.AppendLine("        {");
        code.AppendLine("            // Register marker service for validation in MapErrorOrEndpoints()");
        code.AppendLine("            services.AddSingleton<ErrorOrEndpointsMarkerService>();");

        if (hasValidatableTypes)
        {
            code.AppendLine();
            code.AppendLine(
                "            // Register ErrorOrX validation resolver for .NET 10 validation infrastructure");
            code.AppendLine(
                $"            services.Configure<{WellKnownTypes.Fqn.ValidationOptions}>(static options =>");
            code.AppendLine("            {");
            code.AppendLine("                options.Resolvers.Insert(0, new ErrorOrValidatableInfoResolver());");
            code.AppendLine("            });");
        }

        code.AppendLine("            return new ErrorOrEndpointsBuilder(services);");
        code.AppendLine("        }");
        code.AppendLine();
    }

    private static void EmitOptionsClass(SourceProductionContext spc)
    {
        const string source = """
                              // <auto-generated>
                              // This file was generated by ErrorOr.Generators source generator.
                              // </auto-generated>

                              #nullable enable

                              namespace ErrorOr.Generated
                              {
                                  /// <summary>
                                  /// Marker service to verify that AddErrorOrEndpoints() was called.
                                  /// </summary>
                                  /// <remarks>
                                  /// This follows the ASP.NET Core pattern used by RazorComponentsMarkerService
                                  /// to provide clear error messages when the service registration is missing.
                                  /// </remarks>
                                  internal sealed class ErrorOrEndpointsMarkerService { }

                                  /// <summary>
                                  /// Builder interface for configuring ErrorOr endpoints.
                                  /// </summary>
                                  /// <remarks>
                                  /// This pattern follows ASP.NET Core's IRazorComponentsBuilder design,
                                  /// enabling fluent extension method chaining without callback nesting.
                                  /// </remarks>
                                  public interface IErrorOrEndpointsBuilder
                                  {
                                      /// <summary>
                                      /// Gets the service collection being configured.
                                      /// </summary>
                                      global::Microsoft.Extensions.DependencyInjection.IServiceCollection Services { get; }
                                  }

                                  /// <summary>
                                  /// Default implementation of <see cref="IErrorOrEndpointsBuilder"/>.
                                  /// </summary>
                                  internal sealed class ErrorOrEndpointsBuilder : IErrorOrEndpointsBuilder
                                  {
                                      public ErrorOrEndpointsBuilder(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                                      {
                                          Services = services;
                                      }

                                      public global::Microsoft.Extensions.DependencyInjection.IServiceCollection Services { get; }
                                  }

                                  /// <summary>
                                  /// Extension methods for <see cref="IErrorOrEndpointsBuilder"/>.
                                  /// </summary>
                                  public static class ErrorOrEndpointsBuilderExtensions
                                  {
                                      /// <summary>
                                      /// Registers a JsonSerializerContext for AOT-compatible JSON serialization.
                                      /// </summary>
                                      /// <typeparam name="TContext">The JsonSerializerContext type.</typeparam>
                                      /// <param name="builder">The builder instance.</param>
                                      /// <returns>The builder instance for chaining.</returns>
                                      public static IErrorOrEndpointsBuilder UseJsonContext<TContext>(this IErrorOrEndpointsBuilder builder)
                                          where TContext : global::System.Text.Json.Serialization.JsonSerializerContext, new()
                                      {
                                          builder.Services.ConfigureHttpJsonOptions(options =>
                                          {
                                              options.SerializerOptions.TypeInfoResolverChain.Insert(0, new TContext());
                                          });
                                          return builder;
                                      }

                                      /// <summary>
                                      /// Uses camelCase for JSON property names.
                                      /// </summary>
                                      /// <param name="builder">The builder instance.</param>
                                      /// <param name="enabled">Whether to enable camelCase (default: true).</param>
                                      /// <returns>The builder instance for chaining.</returns>
                                      public static IErrorOrEndpointsBuilder WithCamelCase(this IErrorOrEndpointsBuilder builder, bool enabled = true)
                                      {
                                          if (enabled)
                                          {
                                              builder.Services.ConfigureHttpJsonOptions(options =>
                                              {
                                                  options.SerializerOptions.PropertyNamingPolicy = global::System.Text.Json.JsonNamingPolicy.CamelCase;
                                              });
                                          }
                                          return builder;
                                      }

                                      /// <summary>
                                      /// Ignores null values when serializing JSON.
                                      /// </summary>
                                      /// <param name="builder">The builder instance.</param>
                                      /// <param name="enabled">Whether to ignore nulls (default: true).</param>
                                      /// <returns>The builder instance for chaining.</returns>
                                      public static IErrorOrEndpointsBuilder WithIgnoreNulls(this IErrorOrEndpointsBuilder builder, bool enabled = true)
                                      {
                                          if (enabled)
                                          {
                                              builder.Services.ConfigureHttpJsonOptions(options =>
                                              {
                                                  options.SerializerOptions.DefaultIgnoreCondition = global::System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
                                              });
                                          }
                                          return builder;
                                      }
                                  }

                                  /// <summary>
                                  /// Composite convention builder that applies conventions to multiple endpoints.
                                  /// </summary>
                                  /// <remarks>
                                  /// This follows the ASP.NET Core pattern for applying global conventions
                                  /// to all endpoints registered by MapErrorOrEndpoints().
                                  /// </remarks>
                                  internal sealed class CompositeEndpointConventionBuilder : global::Microsoft.AspNetCore.Builder.IEndpointConventionBuilder
                                  {
                                      private readonly global::System.Collections.Generic.List<global::Microsoft.AspNetCore.Builder.IEndpointConventionBuilder> _builders;

                                      public CompositeEndpointConventionBuilder(global::System.Collections.Generic.List<global::Microsoft.AspNetCore.Builder.IEndpointConventionBuilder> builders)
                                      {
                                          _builders = builders;
                                      }

                                      public void Add(global::System.Action<global::Microsoft.AspNetCore.Builder.EndpointBuilder> convention)
                                      {
                                          foreach (var builder in _builders)
                                          {
                                              builder.Add(convention);
                                          }
                                      }

                                      public void Finally(global::System.Action<global::Microsoft.AspNetCore.Builder.EndpointBuilder> finallyConvention)
                                      {
                                          foreach (var builder in _builders)
                                          {
                                              builder.Finally(finallyConvention);
                                          }
                                      }
                                  }
                              }
                              """;
        spc.AddSource("ErrorOrEndpointOptions.g.cs", SourceText.From(source, Encoding.UTF8));
    }

}
