using ErrorOr.Generators.Emitters;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ErrorOr.Generators;

/// <summary>
///     Code emission entry point for endpoint mappings.
///     Orchestrates the per-emission-phase partials:
///     <list type="bullet">
///         <item><c>Emitter.Versioning.cs</c> — API version set + per-endpoint versioning calls.</item>
///         <item><c>Emitter.Invoker.cs</c> — Per-endpoint wrapper/core method emission and bind helpers.</item>
///         <item><c>Emitter.ErrorHandling.cs</c> — Error-to-ProblemDetails / Results-union dispatch.</item>
///         <item><c>Emitter.JsonContext.cs</c>, <c>Emitter.Options.cs</c>, <c>Emitter.Support.cs</c> — Existing partials.</item>
///     </list>
/// </summary>
public sealed partial class ErrorOrEndpointGenerator
{
    internal static void EmitEndpoints(SourceProductionContext spc, ImmutableArray<EndpointDescriptor> endpoints,
        ImmutableArray<JsonContextInfo> userContexts, int maxArity = 6, bool generateJsonContext = true,
        bool hasValidationResolverSupport = false)
    {
        var sorted = SortEndpoints(endpoints);
        var jsonTypes = CollectJsonTypes(sorted);
        var hasValidatableTypes = hasValidationResolverSupport && HasValidatableTypes(endpoints);

        EmitGlobalUsings(spc);
        EmitOptionsClass(spc);
        EmitMappings(spc, sorted, jsonTypes.Count > 0, maxArity, hasValidatableTypes);

        if (jsonTypes.Count > 0 && generateJsonContext) EmitJsonContext(spc, jsonTypes, userContexts);

        if (hasValidatableTypes) ValidationResolverEmitter.Emit(spc, endpoints);
    }

    private static bool HasValidatableTypes(ImmutableArray<EndpointDescriptor> endpoints)
    {
        foreach (var ep in endpoints)
        foreach (var p in ep.HandlerParameters.AsImmutableArray())
            if (p is { RequiresValidation: true, ValidatableProperties.IsDefaultOrEmpty: false })
                return true;

        return false;
    }

    private static void EmitGlobalUsings(SourceProductionContext spc)
    {
        const string Source = """
                              // <auto-generated/>
                              global using ErrorOr.Generated;
                              """;
        spc.AddSource("ErrorOrEndpoints.GlobalUsings.g.cs", SourceText.From(Source, Encoding.UTF8));
    }

    private static void EmitMappings(SourceProductionContext spc, ImmutableArray<EndpointDescriptor> endpoints,
        bool hasJsonTypes, int maxArity, bool hasValidatableTypes = false)
    {
        var code = new StringBuilder();
        code.AppendLine(GeneratedCodeHelpers.AutoGeneratedHeader("ErrorOr.Generators"));
        if (hasValidatableTypes)
            code.AppendLine("#pragma warning disable ASP0029 // Type is for evaluation purposes only");

        code.AppendLine(GeneratedCodeHelpers.NullableEnable);
        code.AppendLine("using System;");
        code.AppendLine("using System.Linq;");
        code.AppendLine("using System.Threading.Tasks;");
        code.AppendLine("using Microsoft.AspNetCore.Builder;");
        code.AppendLine("using Microsoft.AspNetCore.Http;");
        code.AppendLine("using Microsoft.AspNetCore.Routing;");
        code.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        code.AppendLine();
        code.AppendLine("namespace ErrorOr.Generated");
        code.AppendLine("{");
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// Generated endpoint mappings for all [ErrorOrEndpoint] handlers in this assembly.");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public static class ErrorOrEndpointMappings");
        code.AppendLine("    {");
        code.AppendLine("        /// <summary>");
        code.AppendLine("        /// Maps all ErrorOr endpoints to the application's routing table.");
        code.AppendLine("        /// </summary>");
        code.AppendLine("        /// <param name=\"app\">The endpoint route builder to add mappings to.</param>");
        code.AppendLine(
            "        /// <returns>A convention builder for applying global conventions to all endpoints.</returns>");
        code.AppendLine("        /// <exception cref=\"InvalidOperationException\">");
        code.AppendLine("        /// Thrown when AddErrorOrEndpoints() was not called during service registration.");
        code.AppendLine("        /// </exception>");
        code.AppendLine("        /// <remarks>");
        code.AppendLine("        /// This follows ASP.NET Core's convention builder pattern, enabling global");
        code.AppendLine("        /// endpoint configuration like RequireAuthorization() or RequireRateLimiting().");
        code.AppendLine("        /// </remarks>");
        code.AppendLine("        /// <example>");
        code.AppendLine("        /// <code>");
        code.AppendLine("        /// app.MapErrorOrEndpoints()");
        code.AppendLine("        ///    .RequireAuthorization()");
        code.AppendLine("        ///    .RequireRateLimiting(\"api\");");
        code.AppendLine("        /// </code>");
        code.AppendLine("        /// </example>");
        code.AppendLine(
            "        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2026\",");
        code.AppendLine(
            "            Justification = \"Delegates are generated at compile time with known signatures.\")]");
        code.AppendLine(
            "        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL3050\",");
        code.AppendLine(
            "            Justification = \"Delegates are generated at compile time with known signatures.\")]");
        code.AppendLine(
            "        public static IEndpointConventionBuilder MapErrorOrEndpoints(this IEndpointRouteBuilder app)");
        code.AppendLine("        {");
        code.AppendLine("            // Validate that AddErrorOrEndpoints() was called");
        code.AppendLine("            var marker = app.ServiceProvider.GetService<ErrorOrEndpointsMarkerService>();");
        code.AppendLine("            if (marker is null)");
        code.AppendLine("            {");
        code.AppendLine("                throw new InvalidOperationException(");
        code.AppendLine("                    \"Unable to find the required services. \" +");
        code.AppendLine(
            "                    \"Please add all the required services by calling 'IServiceCollection.AddErrorOrEndpoints()' \" +");
        code.AppendLine("                    \"in the application startup code.\");");
        code.AppendLine("            }");
        code.AppendLine();
        code.AppendLine(
            "            var __endpointBuilders = new System.Collections.Generic.List<IEndpointConventionBuilder>();");
        code.AppendLine();

        // Group endpoints by [RouteGroup] attribute
        var grouping = GroupAggregator.GroupEndpoints(endpoints);

        // Compute global version set for ungrouped endpoints (grouped endpoints use their own version sets)
        var ungroupedEndpoints = grouping.UngroupedEndpoints.AsImmutableArray()
            .Select(static ie => ie.Endpoint)
            .ToImmutableArray();
        var ungroupedVersionSet = ComputeGlobalVersionSet(ungroupedEndpoints);
        if (ungroupedVersionSet.HasVersioning && !ungroupedEndpoints.IsDefaultOrEmpty)
            EmitVersionSet(code, ungroupedVersionSet);

        // Emit route group declarations (eShop-style NewVersionedApi + MapGroup)
        var groupContexts = GroupEmitter.EmitGroupDeclarations(code, grouping.Groups);

        // Emit grouped endpoint mappings
        foreach (var ctx in groupContexts)
        foreach (var indexed in ctx.Group.Endpoints)
            GroupEmitter.EmitGroupedMapCall(code, in indexed, ctx.GroupVariableName, maxArity);

        // Emit ungrouped endpoint mappings (legacy pattern)
        foreach (var indexed in grouping.UngroupedEndpoints)
            EmitMapCall(code, indexed.Endpoint, indexed.OriginalIndex, maxArity, ungroupedVersionSet.HasVersioning);

        code.AppendLine();
        code.AppendLine("            return new CompositeEndpointConventionBuilder(__endpointBuilders);");
        code.AppendLine("        }");
        code.AppendLine();

        if (hasJsonTypes || hasValidatableTypes) EmitAddErrorOrEndpointsExtension(code, hasValidatableTypes);

        // Emit invokers for ALL endpoints (grouped and ungrouped)
        for (var i = 0; i < endpoints.Length; i++)
            EmitInvoker(code, endpoints[i], i, maxArity);

        EmitSupportMethods(code);
        code.AppendLine("    }");
        code.AppendLine("}");

        spc.AddSource("ErrorOrEndpointMappings.cs", SourceText.From(code.ToString(), Encoding.UTF8));
    }

    private static void EmitMapCall(StringBuilder code, in EndpointDescriptor ep, int index, int maxArity,
        bool hasGlobalVersionSet = false)
    {
        code.AppendLine(
            $"            // {ep.HttpMethod} {ep.Pattern} -> {ep.HandlerContainingTypeFqn}.{ep.HandlerMethodName}");

        MapCallEmitter.EmitMapCallStart(code, in ep, "app", ep.Pattern, index, "            ");

        // Emit API versioning fluent calls
        EmitVersioningCalls(code, ep.Versioning, hasGlobalVersionSet);

        // Use shared metadata emitter for consistent output (tags, accepts, produces, middleware)
        EndpointMetadataEmitter.EmitEndpointMetadata(code, in ep, "                ", maxArity);

        MapCallEmitter.EmitMapCallEnd(code, index, "            ");
        code.AppendLine();
    }
}
