using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ErrorOr.Generators;

/// <summary>
///     Source emission for OpenAPI transformers: tag transformers, the operation transformer,
///     the schema transformer, and the AddErrorOrOpenApi registration extension.
/// </summary>
public sealed partial class OpenApiTransformerGenerator
{
    private static void Emit(
        SourceProductionContext spc,
        ImmutableArray<OpenApiEndpointInfo> endpoints,
        ImmutableArray<TypeMetadataInfo> types)
    {
        if (endpoints.IsDefaultOrEmpty) return;

        var code = new StringBuilder();
        code.AppendLine("// <auto-generated/>");
        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine("using System;");
        code.AppendLine("using System.Collections.Frozen;");
        code.AppendLine("using System.Collections.Generic;");
        code.AppendLine("using System.Threading;");
        code.AppendLine("using System.Threading.Tasks;");
        code.AppendLine("using Microsoft.AspNetCore.OpenApi;");
        code.AppendLine("using Microsoft.AspNetCore.Routing;");
        code.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        code.AppendLine("using Microsoft.OpenApi;");
        code.AppendLine();
        code.AppendLine("namespace ErrorOr.Generated;");
        code.AppendLine();

        // Collect unique tags (1 attribute → 1 transformer)
        var tags = endpoints.Select(static e => e.TagName).Distinct(StringComparer.Ordinal)
            .OrderBy(static t => t, StringComparer.Ordinal).ToList();

        // Emit tag transformers (strict 1:1 - one transformer per unique tag)
        foreach (var tag in tags) EmitTagTransformer(code, tag);

        // Emit operation transformer (applies XML doc summaries)
        var hasOperationDocs = EmitOperationTransformer(code, endpoints);

        // Emit schema transformer (applies type descriptions)
        var hasTypeDocs = false;
        if (!types.IsDefaultOrEmpty) hasTypeDocs = EmitSchemaTransformer(code, types);

        // Emit registration extension
        EmitRegistrationExtension(code, tags, hasOperationDocs, hasTypeDocs);

        spc.AddSource("OpenApiTransformers.g.cs", SourceText.From(code.ToString(), Encoding.UTF8));
    }

    private static void EmitTagTransformer(StringBuilder code, string tagName)
    {
        var safeTagName = tagName.SanitizeIdentifier();
        code.AppendLine("/// <summary>");
        code.AppendLine($"/// Document transformer for tag: {tagName}");
        code.AppendLine($"/// Generated from: [ErrorOrEndpoint] attribute on *{tagName}Endpoints class");
        code.AppendLine("/// </summary>");
        code.AppendLine($"file sealed class Tag_{safeTagName}_Transformer : IOpenApiDocumentTransformer");
        code.AppendLine("{");
        code.AppendLine("    public Task TransformAsync(");
        code.AppendLine("        OpenApiDocument document,");
        code.AppendLine("        OpenApiDocumentTransformerContext context,");
        code.AppendLine("        CancellationToken cancellationToken)");
        code.AppendLine("    {");
        // OpenApiDocument.Tags setter auto-wraps with OpenApiTagComparer.Instance
        // which handles deduplication by Name - no manual .Any() check needed
        code.AppendLine("        document.Tags ??= new HashSet<OpenApiTag>();");
        code.AppendLine($"        document.Tags.Add(new OpenApiTag {{ Name = \"{tagName}\" }});");
        code.AppendLine("        return Task.CompletedTask;");
        code.AppendLine("    }");
        code.AppendLine("}");
        code.AppendLine();
    }

    private static bool EmitOperationTransformer(StringBuilder code, ImmutableArray<OpenApiEndpointInfo> endpoints)
    {
        // Collect operations with XML docs (summary/description OR parameter docs)
        var opsWithDocs = endpoints
            .Where(static e => !string.IsNullOrEmpty(e.Summary) || !string.IsNullOrEmpty(e.Description) ||
                               !e.ParameterDocs.IsDefaultOrEmpty)
            .OrderBy(static e => e.Pattern, StringComparer.Ordinal)
            .ThenBy(static e => e.HttpMethod, StringComparer.Ordinal).ToList();

        // Collect operations with OpenAPI parameter definitions
        var opsWithParams = endpoints
            .Where(static e => !e.Parameters.IsDefaultOrEmpty)
            .OrderBy(static e => e.OperationId, StringComparer.Ordinal)
            .ToList();

        if (opsWithDocs.Count is 0 && opsWithParams.Count is 0) return false;

        // Collect operations with parameter docs
        var opsWithParamDocs = opsWithDocs
            .Where(static e => !e.ParameterDocs.IsDefaultOrEmpty)
            .ToList();

        code.AppendLine("/// <summary>");
        code.AppendLine(
            "/// Operation transformer that applies XML documentation and parameter definitions to operations.");
        code.AppendLine("/// Each entry is a strict 1:1 mapping from handler signature to operation metadata.");
        code.AppendLine("/// </summary>");
        code.AppendLine("file sealed class XmlDocOperationTransformer : IOpenApiOperationTransformer");
        code.AppendLine("{");
        code.AppendLine("    // Pre-computed metadata from XML docs (compile-time extraction)");
        code.AppendLine(
            "    private static readonly FrozenDictionary<string, (string? Summary, string? Description)> OperationDocs =");
        code.AppendLine("        new Dictionary<string, (string? Summary, string? Description)>");
        code.AppendLine("        {");

        foreach (var op in opsWithDocs.Where(static e =>
                     !string.IsNullOrEmpty(e.Summary) || !string.IsNullOrEmpty(e.Description)))
        {
            var summary = op.Summary is not null ? $"\"{op.Summary.EscapeCSharpString()}\"" : "null";
            var description = op.Description is not null ? $"\"{op.Description.EscapeCSharpString()}\"" : "null";
            code.AppendLine($"            [\"{op.OperationId}\"] = ({summary}, {description}),");
        }

        code.AppendLine("        }.ToFrozenDictionary(StringComparer.Ordinal);");
        code.AppendLine();

        // Emit parameter docs dictionary
        code.AppendLine("    // Pre-computed parameter descriptions from XML <param> tags");
        code.AppendLine(
            "    private static readonly FrozenDictionary<string, FrozenDictionary<string, string>> ParameterDocs =");
        code.AppendLine("        new Dictionary<string, FrozenDictionary<string, string>>");
        code.AppendLine("        {");

        foreach (var op in opsWithParamDocs)
        {
            code.AppendLine($"            [\"{op.OperationId}\"] = new Dictionary<string, string>");
            code.AppendLine("            {");
            foreach (var (paramName, paramDesc) in op.ParameterDocs.AsImmutableArray())
            {
                code.AppendLine(
                    $"                [\"{paramName.EscapeCSharpString()}\"] = \"{paramDesc.EscapeCSharpString()}\",");
            }

            code.AppendLine("            }.ToFrozenDictionary(StringComparer.Ordinal),");
        }

        code.AppendLine("        }.ToFrozenDictionary(StringComparer.Ordinal);");
        code.AppendLine();

        // Emit parameter definitions dictionary
        if (opsWithParams.Count > 0)
        {
            code.AppendLine("    // Pre-computed parameter definitions from handler signatures");
            code.AppendLine(
                "    private static readonly FrozenDictionary<string, (string Name, ParameterLocation Location, bool Required, JsonSchemaType SchemaType, string? SchemaFormat)[]> ParameterDefs =");
            code.AppendLine(
                "        new Dictionary<string, (string, ParameterLocation, bool, JsonSchemaType, string?)[]>");
            code.AppendLine("        {");

            foreach (var op in opsWithParams)
            {
                code.Append($"            [\"{op.OperationId}\"] = [(");
                var first = true;
                foreach (var p in op.Parameters.AsImmutableArray())
                {
                    if (!first) code.Append("), (");

                    var format = p.SchemaFormat is not null ? $"\"{p.SchemaFormat}\"" : "null";
                    var locationEnum = p.Location switch
                    {
                        "path" => "ParameterLocation.Path",
                        "header" => "ParameterLocation.Header",
                        _ => "ParameterLocation.Query"
                    };
                    var schemaTypeEnum = ToJsonSchemaTypeEnum(p.SchemaType);
                    code.Append(
                        $"\"{p.Name}\", {locationEnum}, {(p.Required ? "true" : "false")}, {schemaTypeEnum}, {format}");
                    first = false;
                }

                code.AppendLine(")],");
            }

            code.AppendLine("        }.ToFrozenDictionary(StringComparer.Ordinal);");
            code.AppendLine();
        }

        code.AppendLine("    public Task TransformAsync(");
        code.AppendLine("        OpenApiOperation operation,");
        code.AppendLine("        OpenApiOperationTransformerContext context,");
        code.AppendLine("        CancellationToken cancellationToken)");
        code.AppendLine("    {");
        code.AppendLine("        string? operationId = null;");
        code.AppendLine("        var metadata = context.Description.ActionDescriptor?.EndpointMetadata;");
        code.AppendLine("        if (metadata is not null)");
        code.AppendLine("        {");
        code.AppendLine("            for (var i = 0; i < metadata.Count; i++)");
        code.AppendLine("            {");
        code.AppendLine("                if (metadata[i] is IEndpointNameMetadata nameMetadata)");
        code.AppendLine("                {");
        code.AppendLine("                    operationId = nameMetadata.EndpointName;");
        code.AppendLine("                    break;");
        code.AppendLine("                }");
        code.AppendLine("            }");
        code.AppendLine("        }");
        code.AppendLine();
        code.AppendLine("        if (operationId is null)");
        code.AppendLine("            return Task.CompletedTask;");
        code.AppendLine();
        code.AppendLine("        // Apply summary and description");
        code.AppendLine("        if (OperationDocs.TryGetValue(operationId, out var docs))");
        code.AppendLine("        {");
        code.AppendLine("            if (docs.Summary is not null)");
        code.AppendLine("                operation.Summary ??= docs.Summary;");
        code.AppendLine("            if (docs.Description is not null)");
        code.AppendLine("                operation.Description ??= docs.Description;");
        code.AppendLine("        }");
        code.AppendLine();

        // Emit parameter definitions application code
        if (opsWithParams.Count > 0)
        {
            code.AppendLine("        // Add parameter definitions from handler signatures");
            code.AppendLine("        if (ParameterDefs.TryGetValue(operationId, out var paramDefs))");
            code.AppendLine("        {");
            code.AppendLine("            operation.Parameters ??= [];");
            code.AppendLine(
                "            foreach (var (pName, pLocation, pRequired, pSchemaType, pSchemaFormat) in paramDefs)");
            code.AppendLine("            {");
            code.AppendLine("                var schema = new OpenApiSchema { Type = pSchemaType };");
            code.AppendLine("                if (pSchemaFormat is not null) schema.Format = pSchemaFormat;");
            code.AppendLine("                operation.Parameters.Add(new OpenApiParameter");
            code.AppendLine("                {");
            code.AppendLine("                    Name = pName,");
            code.AppendLine("                    In = pLocation,");
            code.AppendLine("                    Required = pRequired,");
            code.AppendLine("                    Schema = schema");
            code.AppendLine("                });");
            code.AppendLine("            }");
            code.AppendLine("        }");
            code.AppendLine();
        }

        code.AppendLine("        // Apply parameter descriptions");
        code.AppendLine(
            "        if (ParameterDocs.TryGetValue(operationId, out var paramDocs) && operation.Parameters is not null)");
        code.AppendLine("        {");
        code.AppendLine("            foreach (var param in operation.Parameters)");
        code.AppendLine("            {");
        code.AppendLine(
            "                if (param.Name is not null && paramDocs.TryGetValue(param.Name, out var paramDesc))");
        code.AppendLine("                {");
        code.AppendLine("                    param.Description ??= paramDesc;");
        code.AppendLine("                }");
        code.AppendLine("            }");
        code.AppendLine("        }");
        code.AppendLine();
        code.AppendLine("        return Task.CompletedTask;");
        code.AppendLine("    }");
        code.AppendLine("}");
        code.AppendLine();

        return true;
    }

    private static bool EmitSchemaTransformer(StringBuilder code, ImmutableArray<TypeMetadataInfo> types)
    {
        var typesWithDocs = types.OrderBy(static t => t.TypeKey, StringComparer.Ordinal).ToList();

        if (typesWithDocs.Count is 0) return false;

        code.AppendLine("/// <summary>");
        code.AppendLine("/// Schema transformer that applies type XML documentation to schemas.");
        code.AppendLine("/// Each entry is a strict 1:1 mapping from XML doc to schema description.");
        code.AppendLine("/// AOT-safe: Uses Type as dictionary key (no runtime reflection).");
        code.AppendLine("/// </summary>");
        code.AppendLine("file sealed class XmlDocSchemaTransformer : IOpenApiSchemaTransformer");
        code.AppendLine("{");
        code.AppendLine(
            "    // Pre-computed type descriptions from XML docs (AOT-safe: Type keys resolved at compile-time)");
        code.AppendLine("    private static readonly FrozenDictionary<Type, string> TypeDescriptions =");
        code.AppendLine("        new Dictionary<Type, string>");
        code.AppendLine("        {");

        foreach (var type in typesWithDocs)
        {
            // Convert reflection-style name (Namespace.Outer+Inner) to C# typeof expression (global::Namespace.Outer.Inner)
            var typeofExpr = ConvertToTypeofExpression(type.TypeKey);
            code.AppendLine($"            [typeof({typeofExpr})] = \"{type.Description.EscapeCSharpString()}\",");
        }

        code.AppendLine("        }.ToFrozenDictionary();");
        code.AppendLine();
        code.AppendLine("    public Task TransformAsync(");
        code.AppendLine("        OpenApiSchema schema,");
        code.AppendLine("        OpenApiSchemaTransformerContext context,");
        code.AppendLine("        CancellationToken cancellationToken)");
        code.AppendLine("    {");
        // AOT-safe: Direct Type lookup without reflection
        code.AppendLine("        var type = context.JsonTypeInfo.Type;");
        code.AppendLine("        // For generic types, lookup the generic type definition");
        code.AppendLine("        var lookupType = type.IsGenericType ? type.GetGenericTypeDefinition() : type;");
        code.AppendLine("        if (TypeDescriptions.TryGetValue(lookupType, out var description))");
        code.AppendLine("        {");
        code.AppendLine("            schema.Description ??= description;");
        code.AppendLine("        }");
        code.AppendLine("        return Task.CompletedTask;");
        code.AppendLine("    }");
        code.AppendLine("}");
        code.AppendLine();

        return true;
    }

    private static void EmitRegistrationExtension(
        StringBuilder code,
        List<string> tags,
        bool hasOperationDocs,
        bool hasTypeDocs)
    {
        code.AppendLine("/// <summary>");
        code.AppendLine("/// Extension methods for registering generated OpenAPI transformers.");
        code.AppendLine("/// </summary>");
        code.AppendLine("public static class GeneratedOpenApiExtensions");
        code.AppendLine("{");
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// Adds OpenAPI with generated transformers for ErrorOr endpoints.");
        code.AppendLine("    /// Each transformer is registered following the strict 1:1 mapping rule.");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public static IServiceCollection AddErrorOrOpenApi(");
        code.AppendLine("        this IServiceCollection services,");
        code.AppendLine("        string documentName = \"v1\")");
        code.AppendLine("    {");
        code.AppendLine("        services.AddOpenApi(documentName, options =>");
        code.AppendLine("        {");

        // Register tag transformers (1:1 - one per tag)
        foreach (var tag in tags)
        {
            var safeTagName = tag.SanitizeIdentifier();
            code.AppendLine($"            // Tag: {tag}");
            code.AppendLine($"            options.AddDocumentTransformer(new Tag_{safeTagName}_Transformer());");
        }

        // Register operation transformer if we have docs
        if (hasOperationDocs)
        {
            code.AppendLine();
            code.AppendLine("            // XML doc summaries → operation metadata");
            code.AppendLine("            options.AddOperationTransformer(new XmlDocOperationTransformer());");
        }

        // Register schema transformer if we have type docs
        if (hasTypeDocs)
        {
            code.AppendLine();
            code.AppendLine("            // XML doc summaries → schema descriptions");
            code.AppendLine("            options.AddSchemaTransformer(new XmlDocSchemaTransformer());");
        }

        code.AppendLine("        });");
        code.AppendLine();
        code.AppendLine("        return services;");
        code.AppendLine("    }");
        code.AppendLine("}");
    }
}
